"""
DOCUMENTATION GENERATED BY AI

Django's Command-Line Utility for Administrative Tasks
------------------------------------------------------

This script serves as an entry point for managing a Django project using the
command-line interface. It allows developers to execute various administrative
tasks such as running the development server, running tests, creating database
tables, and creating new apps within the project.

Related Files and Dependencies
------------------------------
1. This script requires Django to be installed in the project's environment.
2. The 'DJANGO_SETTINGS_MODULE' environment variable is set to the project's
   settings module ('openai_toolbox.settings' in this case) as a default value.
3. The 'django.core.management' module is imported to provide the
   'execute_from_command_line' function, which is responsible for parsing and
   executing the command-line arguments.

Key Implementation Details
--------------------------
1. The 'main' function sets the default value for the 'DJANGO_SETTINGS_MODULE'
   environment variable and imports the 'execute_from_command_line' function
   from 'django.core.management'.
2. If Django is not installed or not available in the current environment, an
   ImportError is raised with a helpful message.
3. The 'execute_from_command_line' function is called with 'sys.argv', which
   contains the command-line arguments passed to the script.
4. The '__name__' variable is checked to ensure the script is being run as the
   main module, and if so, the 'main' function is called.

Additional Information
----------------------
1. It is recommended to use a virtual environment when working with Django
   projects to isolate dependencies and ensure consistent behavior across
   different development environments.
2. For a list of available commands and their usage, run this script with the
   'help' argument (e.g., 'python manage.py help').
3. For more information on Django's command-line utility, refer to the
   official documentation: https://docs.djangoproject.com/en/stable/ref/django-admin/


Copyright 2023, Joe Crowley, All rights reserved.
"""
#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys


def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'openai_toolbox.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
