"""
DOCUMENTATION GENERATED BY AI

This module defines the URL patterns for the application.

The main purpose of this code is to create and manage URL routing for the
Django web application. It imports the necessary modules, maps URL paths to
the appropriate views, and provides human-readable names for each path.

Related files and dependencies:
- Django's built-in `path` function is imported from django.urls.
- The `views` module from the current package is imported, which contains the
  implementations of the views connected to the URL patterns.

Location of key implementation details:
- The `urlpatterns` list contains the URL patterns for the application.
  Each entry in the list maps a URL path to a view function and provides a name
  for it.

URL patterns included in the urlpatterns list:
1. `home`: The root URL path ('') maps to the `home` view, displaying the
   homepage of the application.
2. `chat`: The 'chat/' URL path maps to the `submit_message` view, which
   handles sending and receiving messages in the chat interface.
3. `select_conversation`: The 'select_conversation/' URL path maps to the
   `select_conversation` view, allowing users to select an existing
   conversation or create a new one.
4. `save_conversation`: The 'save_conversation/' URL path maps to the
   `save_conversation` view, which handles the saving of conversation data.
5. `dalle`: The 'dalle/' URL path maps to the `dalle` view, which generates
   images using the DALL-E API based on input text.
6. `image_gallery`: The 'image_gallery/' URL path maps to the `image_gallery`
   view, which displays a gallery of images generated by the DALL-E API.

Additional information:
- The `name` parameter in each URL pattern is optional but recommended, as it
  provides a human-readable way to reference the URL in other parts of the
  application (e.g., templates, reverse URL lookups).
- Ensure that any changes to the URL patterns are reflected in the views and
  templates that depend on them to avoid broken links and errors.
- This file should be regularly updated and maintained in accordance with any
  changes to the application's views or desired URL structure.


Copyright 2023, Joe Crowley, All rights reserved.
"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('chat/', views.submit_message, name='chat'),
    path('select_conversation/', views.select_conversation, name='select_conversation'),
    path('save_conversation/', views.save_conversation, name='save_conversation'),
    path('dalle/', views.dalle, name='dalle'),
    path('image_gallery/', views.image_gallery, name='image_gallery'),
]

