"""
DOCUMENTATION GENERATED BY AI

ASGI (Asynchronous Server Gateway Interface) configuration for the "openai_toolbox" project.

This module configures the ASGI application, which is an instance of the Django ASGI
application using the project settings. The main purpose of this code is to create an
entry point for ASGI servers to serve the "openai_toolbox" Django project.

Key functionality:
1. It sets the environment variable 'DJANGO_SETTINGS_MODULE' to 'openai_toolbox.settings'.
2. It creates and exposes the ASGI callable as a module-level variable named 'application'.

Related files and dependencies:
1. This configuration file relies on Django's core ASGI module.
2. It refers to the 'openai_toolbox.settings' module, which contains the project settings.

Location of key implementation details:
1. The 'application' variable is set by calling Django's 'get_asgi_application' function.
2. The 'DJANGO_SETTINGS_MODULE' environment variable is set using the 'os.environ.setdefault' method.

Additional information:
1. To use this ASGI configuration, point your ASGI server to this module. For example, for Daphne:
    daphne openai_toolbox.asgi:application
2. For more information on ASGI configuration and deployment, see:
    https://docs.djangoproject.com/en/3.0/howto/deployment/asgi/



Copyright 2023, Joe Crowley, All rights reserved.
"""
"""
ASGI config for openai_toolbox project.

It exposes the ASGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/howto/deployment/asgi/
"""

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'openai_toolbox.settings')

application = get_asgi_application()
