"""
DOCUMENTATION GENERATED BY AI

Django settings module for the openai_toolbox project.

This module contains the configuration settings for the openai_toolbox Django project.
It is generated by 'django-admin startproject' using Django 3.0.3.

Main functionalities:
- Configures paths, apps, middleware, database, password validation, internationalization, logging, and static files.
- Loads environment variables from a .env file.

Related files and dependencies:
- .env: Contains environment variables, such as the OPENAI_API_KEY.
- dotenv: Package for loading environment variables from the .env file.
- Django: For configuring the web application.

Key implementation details:
- BASE_DIR: Points to the base directory of the project.
- SECRET_KEY: Security key for the project. Make sure to keep this key secret in production.
- DEBUG: Set to True for development purposes, but make sure to set it to False in production.
- INSTALLED_APPS: Lists the Django apps installed in the project.
- MIDDLEWARE: Contains the middleware classes used by the project.
- ROOT_URLCONF: Points to the module containing the project's URL configurations.
- TEMPLATES: Configures the template settings for the project.
- WSGI_APPLICATION: Points to the WSGI application object for the project.
- DATABASES: Sets up the database configuration for the project.
- AUTH_PASSWORD_VALIDATORS: Contains the password validation settings.
- LANGUAGE_CODE, TIME_ZONE, USE_I18N, USE_L10N, USE_TZ: Configures internationalization settings.
- LOGGING: Sets up logging configuration.
- STATIC_URL and STATICFILES_DIRS: Configures the static files settings.
- OPENAI_API_KEY: Loads the OpenAI API key from the environment variable.

Additional information:
- For more information on this file, see https://docs.djangoproject.com/en/3.0/topics/settings/
- For the full list of settings and their values, see https://docs.djangoproject.com/en/3.0/ref/settings/
- Make sure to follow the production deployment checklist: https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/


Copyright 2023, Joe Crowley, All rights reserved.
"""
"""
Django settings for openai_toolbox project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ga4^+*952bi7ijj07v$_(+uk))k8c($&9-vj93@n35v-4!b#-i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'openai_toolbox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'openai_toolbox.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

os.environ.setdefault("OPENAI_API_KEY","")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

