"""
DOCUMENTATION GENERATED BY AI

Django URL Configuration for the Chat Application

This module contains the main URL configuration for the chat application. Its primary purpose is to define and
route the URLs to the appropriate views within the chat app.

Related Files and Dependencies:
-------------------------------
1. chat.urls: The module that defines the URL patterns specific to the chat application. It needs to be imported
   and included in the urlpatterns list.
2. django.urls: Required to use the 'path' and 'include' functions for creating URL patterns and routing.

Key Implementation Details:
---------------------------
1. urlpatterns: A list of URL patterns that are used by Django to route requests to the relevant views. In this case,
   it includes the URL patterns defined in the chat.urls module.
2. path: A function that defines a URL pattern and maps it to a view. It is a part of the 'django.urls' package.
3. include: A function that allows including other URL configurations. It is part of the 'django.urls' package and
   is used here to include the chat.urls module.

Additional Information:
-----------------------
To add or modify URL patterns for the chat application, update the 'chat.urls' module. If new applications are
integrated into the project, include their URL configurations in this module by extending the urlpatterns list.

Make sure to keep the urlpatterns list clean and well-documented for easy maintenance and understanding of the
URL configuration.

Example:
To add a new URL pattern for a view named 'new_view' in an application named 'new_app', follow these steps:
1. Create or update the 'new_app.urls' module to include the URL pattern for 'new_view'.
2. Include the 'new_app.urls' module in the urlpatterns list like this: path('new_app/', include('new_app.urls')).

Note: The first argument to path() function determines the URL path prefix for the included URL patterns. In our
example, the 'new_app/' URL prefix will be added to all the URL patterns defined in 'new_app.urls'.


Copyright 2023, Joe Crowley, All rights reserved.
"""
from django.urls import path, include

urlpatterns = [
    path('', include('chat.urls')),
]

