"""
DOCUMENTATION GENERATED BY AI

WSGI config for openai_toolbox project.

This module configures the WSGI (Web Server Gateway Interface) settings for the
openai_toolbox Django project, allowing it to be served by WSGI-compatible web
servers. It exposes the WSGI callable as a module-level variable named 'application'.

Main Purpose and Functionality:
- Set the 'DJANGO_SETTINGS_MODULE' environment variable to the correct settings
  module for the project.
- Import and configure the 'get_wsgi_application' function from Django's WSGI module.
- Create an instance of the WSGI application to be served by the web server.

Related Files and Dependencies:
- Requires the 'django' package, specifically the 'django.core.wsgi' module.
- Relies on the 'openai_toolbox.settings' module for Django project settings.
- Referenced by the web server configuration file (e.g., 'wsgi.py' for Gunicorn).

Key Implementation Details:
- The 'os.environ.setdefault' function is used to set the 'DJANGO_SETTINGS_MODULE'
  environment variable, defaulting to 'openai_toolbox.settings' if not already set.
- The 'get_wsgi_application' function from Django's WSGI module is called to
  instantiate the WSGI application object.

Additional Information:
- For more information on this file and WSGI configuration in general, see the
  Django documentation:
  https://docs.djangoproject.com/en/stable/howto/deployment/wsgi/

- To deploy the application using a WSGI server, refer to the specific server's
  documentation for proper configuration (e.g., Gunicorn, uWSGI, mod_wsgi, etc.).

- For information on available settings in the 'openai_toolbox.settings' module,
  refer to the Django settings documentation:
  https://docs.djangoproject.com/en/stable/topics/settings/


import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'openai_toolbox.settings')
application = get_wsgi_application()

Copyright 2023, Joe Crowley, All rights reserved.
"""
"""
WSGI config for openai_toolbox project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'openai_toolbox.settings')

application = get_wsgi_application()
